export const LAYOUT_COPY = {
  skip: 'Saltar al contenido',
  brandAria: 'Inicio de Armagedón',
  brandName: 'ARMAGEDÓN',
  brandTagline: 'Forja • Batalla • Leyenda',
  nav: {
    home: 'Inicio',
    shop: 'Forja',
    events: 'Eventos',
    about: 'El deporte',
    admin: 'Admin / Publicar',
  },
  guest: 'Invitado',
  profileAria: 'Abrir perfil',
  signInAria: 'Entrar',
  openCart: 'Abrir carrito',
  openMenu: 'Abrir menú',
  closeMenu: 'Cerrar menú',
  findField: 'Cómo llegar',
  builtBy: 'Hecho por',
  socialNav: 'Redes y contacto',
  instagram: 'Instagram',
  github: 'GitHub',
  githubUrl: 'https://github.com/HugoFernandoColmenares',
  githubAria: 'GitHub de Hugo Colmenares, se abre en una pestaña nueva',
  instagramAria: 'Instagram de Armagedón Softcombat, se abre en una pestaña nueva',
  mapsAria: 'Cómo llegar al Parque La Flora, se abre en una pestaña nueva',
} as const;
