export const NOTIFY_COPY = {
  notAvailable: 'No disponible',
  workshopQueue: 'Esta pieza sigue en la cola del taller.',
  rackLimit: 'Límite del rack',
  onlyAvailable: (stock: number) => `Solo hay ${stock} disponibles ahora.`,
  added: (name: string) => `${name} añadida`,
  signedIn: 'Sesión iniciada',
  passCreated: 'Pase creado',
  registerFailed: 'No se pudo registrar',
  serverRejected: 'El servidor rechazó la solicitud.',
  alreadyRegistered: 'Ya registrado',
  emailHasPass: 'Ese correo ya tiene un pase en este dispositivo.',
  signInFailed: 'No se pudo entrar',
  badCredentials: 'Esas credenciales no coinciden con un pase.',
  reserveTitle: '¿Reservar este arsenal?',
  reserveBody: 'Esto deja una reserva en el taller. El pago y la entrega son en persona, en el campo.',
  reserveConfirm: 'Reservar',
  cancel: 'Cancelar',
  reserveFailed: 'La reserva falló',
  ledgerFailed: 'El libro no pudo tomar el pedido.',
  reserved: 'Reservado',
  bringRef: 'Lleva la referencia al próximo domingo.',
} as const;
